// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file link/v1/link.proto (package otterscale.link.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_feature } from "../../feature_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file link/v1/link.proto.
 */
export const file_link_v1_link: GenFile = /*@__PURE__*/
  fileDesc("ChJsaW5rL3YxL2xpbmsucHJvdG8SEm90dGVyc2NhbGUubGluay52MSIuCgRMaW5rEg8KB2NsdXN0ZXIYASABKAkSFQoNYWdlbnRfdmVyc2lvbhgCIAEoCSISChBMaXN0TGlua3NSZXF1ZXN0IjwKEUxpc3RMaW5rc1Jlc3BvbnNlEicKBWxpbmtzGAEgAygLMhgub3R0ZXJzY2FsZS5saW5rLnYxLkxpbmsiWAoPUmVnaXN0ZXJSZXF1ZXN0Eg8KB2NsdXN0ZXIYASABKAkSCwoDY3NyGAIgASgMEhAKCGFnZW50X2lkGAMgASgJEhUKDWFnZW50X3ZlcnNpb24YBCABKAkiKgoXR2V0QWdlbnRNYW5pZmVzdFJlcXVlc3QSDwoHY2x1c3RlchgBIAEoCSI5ChhHZXRBZ2VudE1hbmlmZXN0UmVzcG9uc2USEAoIbWFuaWZlc3QYASABKAkSCwoDdXJsGAIgASgJImkKEFJlZ2lzdGVyUmVzcG9uc2USEAoIZW5kcG9pbnQYASABKAkSEwoLY2VydGlmaWNhdGUYAiABKAwSFgoOY2FfY2VydGlmaWNhdGUYAyABKAwSFgoOc2VydmVyX3ZlcnNpb24YBCABKAky8AIKC0xpbmtTZXJ2aWNlEm0KCUxpc3RMaW5rcxIkLm90dGVyc2NhbGUubGluay52MS5MaXN0TGlua3NSZXF1ZXN0GiUub3R0ZXJzY2FsZS5saW5rLnYxLkxpc3RMaW5rc1Jlc3BvbnNlIhOK39UdDgoMbGluay1lbmFibGVkEmoKCFJlZ2lzdGVyEiMub3R0ZXJzY2FsZS5saW5rLnYxLlJlZ2lzdGVyUmVxdWVzdBokLm90dGVyc2NhbGUubGluay52MS5SZWdpc3RlclJlc3BvbnNlIhOK39UdDgoMbGluay1lbmFibGVkEoUBChBHZXRBZ2VudE1hbmlmZXN0Eisub3R0ZXJzY2FsZS5saW5rLnYxLkdldEFnZW50TWFuaWZlc3RSZXF1ZXN0Giwub3R0ZXJzY2FsZS5saW5rLnYxLkdldEFnZW50TWFuaWZlc3RSZXNwb25zZSIWkAIBit/VHQ4KDGxpbmstZW5hYmxlZEIqWihnaXRodWIuY29tL290dGVyc2NhbGUvYXBpL2xpbmsvdjE7bGlua3YxYghlZGl0aW9uc3DoBw", [file_feature]);

/**
 * @generated from message otterscale.link.v1.Link
 */
export type Link = Message<"otterscale.link.v1.Link"> & {
  /**
   * The cluster name.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * The version of the agent binary (e.g. "v1.2.3"), set at build time.
   *
   * @generated from field: string agent_version = 2;
   */
  agentVersion: string;
};

/**
 * Describes the message otterscale.link.v1.Link.
 * Use `create(LinkSchema)` to create a new message.
 */
export const LinkSchema: GenMessage<Link> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 0);

/**
 * ListLinksRequest is an empty request message for listing links.
 *
 * @generated from message otterscale.link.v1.ListLinksRequest
 */
export type ListLinksRequest = Message<"otterscale.link.v1.ListLinksRequest"> & {
};

/**
 * Describes the message otterscale.link.v1.ListLinksRequest.
 * Use `create(ListLinksRequestSchema)` to create a new message.
 */
export const ListLinksRequestSchema: GenMessage<ListLinksRequest> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 1);

/**
 * ListLinksResponse contains the list of links the agent is registered to.
 *
 * @generated from message otterscale.link.v1.ListLinksResponse
 */
export type ListLinksResponse = Message<"otterscale.link.v1.ListLinksResponse"> & {
  /**
   * The list of links.
   *
   * @generated from field: repeated otterscale.link.v1.Link links = 1;
   */
  links: Link[];
};

/**
 * Describes the message otterscale.link.v1.ListLinksResponse.
 * Use `create(ListLinksResponseSchema)` to create a new message.
 */
export const ListLinksResponseSchema: GenMessage<ListLinksResponse> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 2);

/**
 * RegisterRequest contains the agent's cluster identity and a CSR for
 * mTLS certificate issuance.
 *
 * @generated from message otterscale.link.v1.RegisterRequest
 */
export type RegisterRequest = Message<"otterscale.link.v1.RegisterRequest"> & {
  /**
   * The cluster identifier this agent belongs to.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * PEM-encoded PKCS#10 certificate signing request. The server signs
   * this with its internal CA and returns the issued certificate.
   *
   * @generated from field: bytes csr = 2;
   */
  csr: Uint8Array;

  /**
   * The agent identifier this agent uses to register with the server.
   *
   * @generated from field: string agent_id = 3;
   */
  agentId: string;

  /**
   * The version of the agent binary (e.g. "v1.2.3"), set at build time.
   *
   * @generated from field: string agent_version = 4;
   */
  agentVersion: string;
};

/**
 * Describes the message otterscale.link.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 3);

/**
 * GetAgentManifestRequest identifies the target cluster for which
 * the agent installation manifest should be generated.
 *
 * @generated from message otterscale.link.v1.GetAgentManifestRequest
 */
export type GetAgentManifestRequest = Message<"otterscale.link.v1.GetAgentManifestRequest"> & {
  /**
   * The cluster name the agent will register under.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;
};

/**
 * Describes the message otterscale.link.v1.GetAgentManifestRequest.
 * Use `create(GetAgentManifestRequestSchema)` to create a new message.
 */
export const GetAgentManifestRequestSchema: GenMessage<GetAgentManifestRequest> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 4);

/**
 * GetAgentManifestResponse contains the multi-document YAML manifest
 * that can be applied via kubectl to install the agent.
 *
 * @generated from message otterscale.link.v1.GetAgentManifestResponse
 */
export type GetAgentManifestResponse = Message<"otterscale.link.v1.GetAgentManifestResponse"> & {
  /**
   * Multi-document YAML containing Namespace, ServiceAccount,
   * ClusterRoleBinding, and Deployment resources.
   *
   * @generated from field: string manifest = 1;
   */
  manifest: string;

  /**
   * URL with an embedded HMAC token that serves the manifest as raw
   * YAML. Users can run `kubectl apply -f <url>` directly.
   *
   * @generated from field: string url = 2;
   */
  url: string;
};

/**
 * Describes the message otterscale.link.v1.GetAgentManifestResponse.
 * Use `create(GetAgentManifestResponseSchema)` to create a new message.
 */
export const GetAgentManifestResponseSchema: GenMessage<GetAgentManifestResponse> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 5);

/**
 * RegisterResponse contains a CA-signed certificate and the CA
 * certificate so the agent can establish an mTLS tunnel connection.
 *
 * @generated from message otterscale.link.v1.RegisterResponse
 */
export type RegisterResponse = Message<"otterscale.link.v1.RegisterResponse"> & {
  /**
   * The loopback endpoint reserved for this cluster tunnel.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * PEM-encoded X.509 certificate signed by the server's CA.
   *
   * @generated from field: bytes certificate = 2;
   */
  certificate: Uint8Array;

  /**
   * PEM-encoded CA certificate for verifying the tunnel server.
   *
   * @generated from field: bytes ca_certificate = 3;
   */
  caCertificate: Uint8Array;

  /**
   * The version of the server binary (e.g. "v1.2.3"), set at build time.
   * Agents compare this against their own version to decide whether a
   * self-update is needed.
   *
   * @generated from field: string server_version = 4;
   */
  serverVersion: string;
};

/**
 * Describes the message otterscale.link.v1.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_link_v1_link, 6);

/**
 * LinkService manages the lifecycle of agent-to-server tunnel connections,
 * including registration and health checking.
 *
 * @generated from service otterscale.link.v1.LinkService
 */
export const LinkService: GenService<{
  /**
   * ListLinks returns all cluster identifiers that the current agent
   * is registered to. This is used to discover which clusters are available
   * for tunnel connections.
   *
   * @generated from rpc otterscale.link.v1.LinkService.ListLinks
   */
  listLinks: {
    methodKind: "unary";
    input: typeof ListLinksRequestSchema;
    output: typeof ListLinksResponseSchema;
  },
  /**
   * Register allows an agent to register itself with the tunnel server.
   * The agent sends its cluster identity and tunnel port; the server responds
   * with its fingerprint so the agent can verify the tunnel connection.
   *
   * @generated from rpc otterscale.link.v1.LinkService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * GetAgentManifest returns a multi-document YAML manifest for installing
   * the otterscale agent on a target Kubernetes cluster. The manifest
   * includes a Namespace, ServiceAccount, ClusterRoleBinding (binding the
   * caller to cluster-admin), and a Deployment running the agent.
   *
   * @generated from rpc otterscale.link.v1.LinkService.GetAgentManifest
   */
  getAgentManifest: {
    methodKind: "unary";
    input: typeof GetAgentManifestRequestSchema;
    output: typeof GetAgentManifestResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_link_v1_link, 0);

