# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/addons.otterscale.io_modules.yaml
  - bases/addons.otterscale.io_moduletemplates.yaml
  - bases/apps.otterscale.io_simpleapps.yaml
  - bases/model.otterscale.io_modelartifacts.yaml
  - bases/tenant.otterscale.io_workspaces.yaml
