# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/module.otterscale.io_modules.yaml
  - bases/module.otterscale.io_moduleclasses.yaml
  - bases/workload.otterscale.io_applications.yaml
  - bases/fleet.otterscale.io_clusters.yaml
  - bases/fleet.otterscale.io_machines.yaml
  - bases/model.otterscale.io_artifacts.yaml
  - bases/tenant.otterscale.io_workspaces.yaml
