// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resource/v1/resource.proto

package pb

import (
	_ "github.com/otterscale/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type defines the possible types of events from Kubernetes watch.
type WatchEvent_Type int32

const (
	// Unspecified event type (default zero value).
	WatchEvent_TYPE_UNSPECIFIED WatchEvent_Type = 0
	// A resource was added.
	WatchEvent_TYPE_ADDED WatchEvent_Type = 1
	// A resource was modified.
	WatchEvent_TYPE_MODIFIED WatchEvent_Type = 2
	// A resource was deleted.
	WatchEvent_TYPE_DELETED WatchEvent_Type = 3
	// A bookmark event carrying only a resourceVersion (no resource payload).
	WatchEvent_TYPE_BOOKMARK WatchEvent_Type = 4
	// An error occurred on the server side.
	WatchEvent_TYPE_ERROR WatchEvent_Type = 5
)

// Enum value maps for WatchEvent_Type.
var (
	WatchEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ADDED",
		2: "TYPE_MODIFIED",
		3: "TYPE_DELETED",
		4: "TYPE_BOOKMARK",
		5: "TYPE_ERROR",
	}
	WatchEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_ADDED":       1,
		"TYPE_MODIFIED":    2,
		"TYPE_DELETED":     3,
		"TYPE_BOOKMARK":    4,
		"TYPE_ERROR":       5,
	}
)

func (x WatchEvent_Type) Enum() *WatchEvent_Type {
	p := new(WatchEvent_Type)
	*p = x
	return p
}

func (x WatchEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_v1_resource_proto_enumTypes[0].Descriptor()
}

func (WatchEvent_Type) Type() protoreflect.EnumType {
	return &file_resource_v1_resource_proto_enumTypes[0]
}

func (x WatchEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_Type.Descriptor instead.
func (WatchEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{14, 0}
}

// APIResource represents a Kubernetes API resource with its metadata.
type APIResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources).
	Group *string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	// The kind of the resource (e.g., "Pod", "Deployment").
	Kind *string `protobuf:"bytes,4,opt,name=kind" json:"kind,omitempty"`
	// Whether this resource is namespace-scoped.
	Namespaced *bool `protobuf:"varint,5,opt,name=namespaced" json:"namespaced,omitempty"`
	// The list of supported verbs (e.g., "get", "list", "create", "delete").
	Verbs []string `protobuf:"bytes,6,rep,name=verbs" json:"verbs,omitempty"`
	// Abbreviated aliases for the resource (e.g., "deploy" for deployments).
	ShortNames    []string `protobuf:"bytes,7,rep,name=short_names,json=shortNames" json:"short_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResource) Reset() {
	*x = APIResource{}
	mi := &file_resource_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResource) ProtoMessage() {}

func (x *APIResource) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResource.ProtoReflect.Descriptor instead.
func (*APIResource) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *APIResource) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *APIResource) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *APIResource) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *APIResource) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *APIResource) GetNamespaced() bool {
	if x != nil && x.Namespaced != nil {
		return *x.Namespaced
	}
	return false
}

func (x *APIResource) GetVerbs() []string {
	if x != nil {
		return x.Verbs
	}
	return nil
}

func (x *APIResource) GetShortNames() []string {
	if x != nil {
		return x.ShortNames
	}
	return nil
}

// DiscoveryRequest defines the parameters for discovering API resources.
type DiscoveryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster       *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

// DiscoveryResponse contains the list of available API resources in the cluster.
type DiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of available API resources in the cluster.
	ApiResources  []*APIResource `protobuf:"bytes,1,rep,name=api_resources,json=apiResources" json:"api_resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_resource_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoveryResponse) GetApiResources() []*APIResource {
	if x != nil {
		return x.ApiResources
	}
	return nil
}

// SchemaRequest defines the parameters to retrieve the schema of a specific GVK.
type SchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Kind (e.g., "Pod").
	Kind          *string `protobuf:"bytes,4,opt,name=kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRequest) Reset() {
	*x = SchemaRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRequest) ProtoMessage() {}

func (x *SchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRequest.ProtoReflect.Descriptor instead.
func (*SchemaRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *SchemaRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *SchemaRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *SchemaRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

// Resource represents a single Kubernetes object serialized as a JSON string.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full JSON representation of the Kubernetes object.
	// Note: Backend may strip managedFields to reduce payload size.
	Object        *structpb.Struct `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_resource_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetObject() *structpb.Struct {
	if x != nil {
		return x.Object
	}
	return nil
}

// ListRequest defines the parameters for querying multiple resources.
type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace to query. If empty, the request may target all namespaces depending on cluster permissions.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// A selector to restrict the list of returned objects by their labels.
	LabelSelector *string `protobuf:"bytes,6,opt,name=label_selector,json=labelSelector" json:"label_selector,omitempty"`
	// A selector to restrict the list of returned objects by their fields (e.g., "status.phase=Running").
	FieldSelector *string `protobuf:"bytes,7,opt,name=field_selector,json=fieldSelector" json:"field_selector,omitempty"`
	// The maximum number of items to return in a single page.
	Limit *int64 `protobuf:"varint,8,opt,name=limit" json:"limit,omitempty"`
	// The continue token for pagination, retrieved from a previous ListResponse.
	Continue      *string `protobuf:"bytes,9,opt,name=continue" json:"continue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ListRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *ListRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ListRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *ListRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListRequest) GetLabelSelector() string {
	if x != nil && x.LabelSelector != nil {
		return *x.LabelSelector
	}
	return ""
}

func (x *ListRequest) GetFieldSelector() string {
	if x != nil && x.FieldSelector != nil {
		return *x.FieldSelector
	}
	return ""
}

func (x *ListRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListRequest) GetContinue() string {
	if x != nil && x.Continue != nil {
		return *x.Continue
	}
	return ""
}

// ListResponse contains the requested list of resources and pagination metadata.
type ListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resourceVersion of the list, used to initiate a Watch from a specific point in time.
	ResourceVersion *string `protobuf:"bytes,1,opt,name=resource_version,json=resourceVersion" json:"resource_version,omitempty"`
	// A token used to retrieve the next page of results. Empty if no more pages exist.
	Continue *string `protobuf:"bytes,2,opt,name=continue" json:"continue,omitempty"`
	// The estimated number of items remaining if pagination is used.
	RemainingItemCount *int64 `protobuf:"varint,3,opt,name=remaining_item_count,json=remainingItemCount" json:"remaining_item_count,omitempty"`
	// The list of resources found.
	Items         []*Resource `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_resource_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetResourceVersion() string {
	if x != nil && x.ResourceVersion != nil {
		return *x.ResourceVersion
	}
	return ""
}

func (x *ListResponse) GetContinue() string {
	if x != nil && x.Continue != nil {
		return *x.Continue
	}
	return ""
}

func (x *ListResponse) GetRemainingItemCount() int64 {
	if x != nil && x.RemainingItemCount != nil {
		return *x.RemainingItemCount
	}
	return 0
}

func (x *ListResponse) GetItems() []*Resource {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetRequest defines the parameters to fetch a single object.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the resource.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the resource.
	Name          *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *GetRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *GetRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *GetRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *GetRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *GetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// DescribeRequest defines the parameters to describe a resource, retrieving
// it along with its related Kubernetes events. Equivalent to `kubectl describe`.
type DescribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the resource.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the resource.
	Name          *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *DescribeRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *DescribeRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *DescribeRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *DescribeRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *DescribeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// DescribeResponse contains the resource and its related Kubernetes events.
type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full resource object.
	Resource *Resource `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	// Kubernetes events related to this resource, filtered by involvedObject.uid.
	Events        []*Resource `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_resource_v1_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{9}
}

func (x *DescribeResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DescribeResponse) GetEvents() []*Resource {
	if x != nil {
		return x.Events
	}
	return nil
}

// CreateRequest defines the parameters for creating a new object.
type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the resource.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The full manifest of the object to be created in YAML format.
	Manifest      []byte `protobuf:"bytes,6,opt,name=manifest" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *CreateRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *CreateRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *CreateRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *CreateRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *CreateRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// ApplyRequest defines the parameters for Server-Side Apply (SSA).
type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the resource.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the resource.
	Name *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	// A partial or YAML manifest in JSON format to be merged by the API server.
	Manifest []byte `protobuf:"bytes,7,opt,name=manifest" json:"manifest,omitempty"`
	// If true, conflicts are resolved in favour of the caller's field manager.
	Force *bool `protobuf:"varint,8,opt,name=force" json:"force,omitempty"`
	// Identifies the entity managing the fields (e.g., "otterscale-web-ui"). Required for SSA.
	FieldManager  *string `protobuf:"bytes,9,opt,name=field_manager,json=fieldManager" json:"field_manager,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ApplyRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *ApplyRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ApplyRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *ApplyRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ApplyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ApplyRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ApplyRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *ApplyRequest) GetFieldManager() string {
	if x != nil && x.FieldManager != nil {
		return *x.FieldManager
	}
	return ""
}

// DeleteRequest defines the parameters to remove an object.
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the resource.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the resource.
	Name *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	// The duration in seconds before the object should be deleted. Overrides the default grace period.
	GracePeriodSeconds *int64 `protobuf:"varint,7,opt,name=grace_period_seconds,json=gracePeriodSeconds" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *DeleteRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *DeleteRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *DeleteRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DeleteRequest) GetGracePeriodSeconds() int64 {
	if x != nil && x.GracePeriodSeconds != nil {
		return *x.GracePeriodSeconds
	}
	return 0
}

// WatchRequest defines the parameters to start a streaming watch.
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps" for Deployments, "" for core resources like Pods).
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "pods", "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace to watch.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// A selector to restrict watched objects by their labels.
	LabelSelector *string `protobuf:"bytes,6,opt,name=label_selector,json=labelSelector" json:"label_selector,omitempty"`
	// A selector to restrict watched objects by their fields.
	FieldSelector *string `protobuf:"bytes,7,opt,name=field_selector,json=fieldSelector" json:"field_selector,omitempty"`
	// Start the watch from this specific resource version.
	ResourceVersion *string `protobuf:"bytes,8,opt,name=resource_version,json=resourceVersion" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_resource_v1_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{13}
}

func (x *WatchRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *WatchRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *WatchRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *WatchRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *WatchRequest) GetLabelSelector() string {
	if x != nil && x.LabelSelector != nil {
		return *x.LabelSelector
	}
	return ""
}

func (x *WatchRequest) GetFieldSelector() string {
	if x != nil && x.FieldSelector != nil {
		return *x.FieldSelector
	}
	return ""
}

func (x *WatchRequest) GetResourceVersion() string {
	if x != nil && x.ResourceVersion != nil {
		return *x.ResourceVersion
	}
	return ""
}

// WatchEvent represents a single change notification from the Kubernetes API.
type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the watch event.
	Type *WatchEvent_Type `protobuf:"varint,1,opt,name=type,enum=otterscale.resource.v1.WatchEvent_Type" json:"type,omitempty"`
	// The state of the resource associated with the event.
	Resource *Resource `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	// The resourceVersion of the watch event, used to initiate a Watch from a specific point in time.
	ResourceVersion *string `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_resource_v1_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_resource_v1_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_resource_v1_resource_proto_rawDescGZIP(), []int{14}
}

func (x *WatchEvent) GetType() WatchEvent_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return WatchEvent_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *WatchEvent) GetResourceVersion() string {
	if x != nil && x.ResourceVersion != nil {
		return *x.ResourceVersion
	}
	return ""
}

var File_resource_v1_resource_proto protoreflect.FileDescriptor

const file_resource_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1aresource/v1/resource.proto\x12\x16otterscale.resource.v1\x1a\rfeature.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x01\n" +
	"\vAPIResource\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"namespaced\x18\x05 \x01(\bR\n" +
	"namespaced\x12\x14\n" +
	"\x05verbs\x18\x06 \x03(\tR\x05verbs\x12\x1f\n" +
	"\vshort_names\x18\a \x03(\tR\n" +
	"shortNames\",\n" +
	"\x10DiscoveryRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"]\n" +
	"\x11DiscoveryResponse\x12H\n" +
	"\rapi_resources\x18\x01 \x03(\v2#.otterscale.resource.v1.APIResourceR\fapiResources\"m\n" +
	"\rSchemaRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\";\n" +
	"\bResource\x12/\n" +
	"\x06object\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06object\"\x91\x02\n" +
	"\vListRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x06 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\a \x01(\tR\rfieldSelector\x12\x14\n" +
	"\x05limit\x18\b \x01(\x03R\x05limit\x12\x1a\n" +
	"\bcontinue\x18\t \x01(\tR\bcontinue\"\xbf\x01\n" +
	"\fListResponse\x12)\n" +
	"\x10resource_version\x18\x01 \x01(\tR\x0fresourceVersion\x12\x1a\n" +
	"\bcontinue\x18\x02 \x01(\tR\bcontinue\x120\n" +
	"\x14remaining_item_count\x18\x03 \x01(\x03R\x12remainingItemCount\x126\n" +
	"\x05items\x18\x04 \x03(\v2 .otterscale.resource.v1.ResourceR\x05items\"\xa4\x01\n" +
	"\n" +
	"GetRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\xa9\x01\n" +
	"\x0fDescribeRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x10DescribeResponse\x12<\n" +
	"\bresource\x18\x01 \x01(\v2 .otterscale.resource.v1.ResourceR\bresource\x128\n" +
	"\x06events\x18\x02 \x03(\v2 .otterscale.resource.v1.ResourceR\x06events\"\xaf\x01\n" +
	"\rCreateRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bmanifest\x18\x06 \x01(\fR\bmanifest\"\xfd\x01\n" +
	"\fApplyRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1a\n" +
	"\bmanifest\x18\a \x01(\fR\bmanifest\x12\x14\n" +
	"\x05force\x18\b \x01(\bR\x05force\x12#\n" +
	"\rfield_manager\x18\t \x01(\tR\ffieldManager\"\xd9\x01\n" +
	"\rDeleteRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x120\n" +
	"\x14grace_period_seconds\x18\a \x01(\x03R\x12gracePeriodSeconds\"\x8b\x02\n" +
	"\fWatchRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12%\n" +
	"\x0elabel_selector\x18\x06 \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\a \x01(\tR\rfieldSelector\x12)\n" +
	"\x10resource_version\x18\b \x01(\tR\x0fresourceVersion\"\xa8\x02\n" +
	"\n" +
	"WatchEvent\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.otterscale.resource.v1.WatchEvent.TypeR\x04type\x12<\n" +
	"\bresource\x18\x02 \x01(\v2 .otterscale.resource.v1.ResourceR\bresource\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\"t\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_ADDED\x10\x01\x12\x11\n" +
	"\rTYPE_MODIFIED\x10\x02\x12\x10\n" +
	"\fTYPE_DELETED\x10\x03\x12\x11\n" +
	"\rTYPE_BOOKMARK\x10\x04\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x052\xdf\a\n" +
	"\x0fResourceService\x12y\n" +
	"\tDiscovery\x12(.otterscale.resource.v1.DiscoveryRequest\x1a).otterscale.resource.v1.DiscoveryResponse\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12a\n" +
	"\x06Schema\x12%.otterscale.resource.v1.SchemaRequest\x1a\x17.google.protobuf.Struct\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12j\n" +
	"\x04List\x12#.otterscale.resource.v1.ListRequest\x1a$.otterscale.resource.v1.ListResponse\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12d\n" +
	"\x03Get\x12\".otterscale.resource.v1.GetRequest\x1a .otterscale.resource.v1.Resource\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12v\n" +
	"\bDescribe\x12'.otterscale.resource.v1.DescribeRequest\x1a(.otterscale.resource.v1.DescribeResponse\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12j\n" +
	"\x06Create\x12%.otterscale.resource.v1.CreateRequest\x1a .otterscale.resource.v1.Resource\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12h\n" +
	"\x05Apply\x12$.otterscale.resource.v1.ApplyRequest\x1a .otterscale.resource.v1.Resource\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12`\n" +
	"\x06Delete\x12%.otterscale.resource.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled\x12l\n" +
	"\x05Watch\x12$.otterscale.resource.v1.WatchRequest\x1a\".otterscale.resource.v1.WatchEvent\"\x17\x8a\xdf\xd5\x1d\x12\n" +
	"\x10resource-enabled0\x01B*Z(github.com/otterscale/api/resource/v1;pbb\beditionsp\xe8\a"

var (
	file_resource_v1_resource_proto_rawDescOnce sync.Once
	file_resource_v1_resource_proto_rawDescData []byte
)

func file_resource_v1_resource_proto_rawDescGZIP() []byte {
	file_resource_v1_resource_proto_rawDescOnce.Do(func() {
		file_resource_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_v1_resource_proto_rawDesc), len(file_resource_v1_resource_proto_rawDesc)))
	})
	return file_resource_v1_resource_proto_rawDescData
}

var file_resource_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_resource_v1_resource_proto_goTypes = []any{
	(WatchEvent_Type)(0),      // 0: otterscale.resource.v1.WatchEvent.Type
	(*APIResource)(nil),       // 1: otterscale.resource.v1.APIResource
	(*DiscoveryRequest)(nil),  // 2: otterscale.resource.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil), // 3: otterscale.resource.v1.DiscoveryResponse
	(*SchemaRequest)(nil),     // 4: otterscale.resource.v1.SchemaRequest
	(*Resource)(nil),          // 5: otterscale.resource.v1.Resource
	(*ListRequest)(nil),       // 6: otterscale.resource.v1.ListRequest
	(*ListResponse)(nil),      // 7: otterscale.resource.v1.ListResponse
	(*GetRequest)(nil),        // 8: otterscale.resource.v1.GetRequest
	(*DescribeRequest)(nil),   // 9: otterscale.resource.v1.DescribeRequest
	(*DescribeResponse)(nil),  // 10: otterscale.resource.v1.DescribeResponse
	(*CreateRequest)(nil),     // 11: otterscale.resource.v1.CreateRequest
	(*ApplyRequest)(nil),      // 12: otterscale.resource.v1.ApplyRequest
	(*DeleteRequest)(nil),     // 13: otterscale.resource.v1.DeleteRequest
	(*WatchRequest)(nil),      // 14: otterscale.resource.v1.WatchRequest
	(*WatchEvent)(nil),        // 15: otterscale.resource.v1.WatchEvent
	(*structpb.Struct)(nil),   // 16: google.protobuf.Struct
	(*emptypb.Empty)(nil),     // 17: google.protobuf.Empty
}
var file_resource_v1_resource_proto_depIdxs = []int32{
	1,  // 0: otterscale.resource.v1.DiscoveryResponse.api_resources:type_name -> otterscale.resource.v1.APIResource
	16, // 1: otterscale.resource.v1.Resource.object:type_name -> google.protobuf.Struct
	5,  // 2: otterscale.resource.v1.ListResponse.items:type_name -> otterscale.resource.v1.Resource
	5,  // 3: otterscale.resource.v1.DescribeResponse.resource:type_name -> otterscale.resource.v1.Resource
	5,  // 4: otterscale.resource.v1.DescribeResponse.events:type_name -> otterscale.resource.v1.Resource
	0,  // 5: otterscale.resource.v1.WatchEvent.type:type_name -> otterscale.resource.v1.WatchEvent.Type
	5,  // 6: otterscale.resource.v1.WatchEvent.resource:type_name -> otterscale.resource.v1.Resource
	2,  // 7: otterscale.resource.v1.ResourceService.Discovery:input_type -> otterscale.resource.v1.DiscoveryRequest
	4,  // 8: otterscale.resource.v1.ResourceService.Schema:input_type -> otterscale.resource.v1.SchemaRequest
	6,  // 9: otterscale.resource.v1.ResourceService.List:input_type -> otterscale.resource.v1.ListRequest
	8,  // 10: otterscale.resource.v1.ResourceService.Get:input_type -> otterscale.resource.v1.GetRequest
	9,  // 11: otterscale.resource.v1.ResourceService.Describe:input_type -> otterscale.resource.v1.DescribeRequest
	11, // 12: otterscale.resource.v1.ResourceService.Create:input_type -> otterscale.resource.v1.CreateRequest
	12, // 13: otterscale.resource.v1.ResourceService.Apply:input_type -> otterscale.resource.v1.ApplyRequest
	13, // 14: otterscale.resource.v1.ResourceService.Delete:input_type -> otterscale.resource.v1.DeleteRequest
	14, // 15: otterscale.resource.v1.ResourceService.Watch:input_type -> otterscale.resource.v1.WatchRequest
	3,  // 16: otterscale.resource.v1.ResourceService.Discovery:output_type -> otterscale.resource.v1.DiscoveryResponse
	16, // 17: otterscale.resource.v1.ResourceService.Schema:output_type -> google.protobuf.Struct
	7,  // 18: otterscale.resource.v1.ResourceService.List:output_type -> otterscale.resource.v1.ListResponse
	5,  // 19: otterscale.resource.v1.ResourceService.Get:output_type -> otterscale.resource.v1.Resource
	10, // 20: otterscale.resource.v1.ResourceService.Describe:output_type -> otterscale.resource.v1.DescribeResponse
	5,  // 21: otterscale.resource.v1.ResourceService.Create:output_type -> otterscale.resource.v1.Resource
	5,  // 22: otterscale.resource.v1.ResourceService.Apply:output_type -> otterscale.resource.v1.Resource
	17, // 23: otterscale.resource.v1.ResourceService.Delete:output_type -> google.protobuf.Empty
	15, // 24: otterscale.resource.v1.ResourceService.Watch:output_type -> otterscale.resource.v1.WatchEvent
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_resource_v1_resource_proto_init() }
func file_resource_v1_resource_proto_init() {
	if File_resource_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_v1_resource_proto_rawDesc), len(file_resource_v1_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_resource_v1_resource_proto_depIdxs,
		EnumInfos:         file_resource_v1_resource_proto_enumTypes,
		MessageInfos:      file_resource_v1_resource_proto_msgTypes,
	}.Build()
	File_resource_v1_resource_proto = out.File
	file_resource_v1_resource_proto_goTypes = nil
	file_resource_v1_resource_proto_depIdxs = nil
}
