// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: link/v1/link.proto

package pb

import (
	_ "github.com/otterscale/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster name.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// The version of the agent binary (e.g. "v1.2.3"), set at build time.
	AgentVersion  *string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_link_v1_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *Link) GetAgentVersion() string {
	if x != nil && x.AgentVersion != nil {
		return *x.AgentVersion
	}
	return ""
}

// ListLinksRequest is an empty request message for listing links.
type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_link_v1_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{1}
}

// ListLinksResponse contains the list of links the agent is registered to.
type ListLinksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of links.
	Links         []*Link `protobuf:"bytes,1,rep,name=links" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_link_v1_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{2}
}

func (x *ListLinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// RegisterRequest contains the agent's cluster identity and a CSR for
// mTLS certificate issuance.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster identifier this agent belongs to.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// PEM-encoded PKCS#10 certificate signing request. The server signs
	// this with its internal CA and returns the issued certificate.
	Csr []byte `protobuf:"bytes,2,opt,name=csr" json:"csr,omitempty"`
	// The agent identifier this agent uses to register with the server.
	AgentId *string `protobuf:"bytes,3,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	// The version of the agent binary (e.g. "v1.2.3"), set at build time.
	AgentVersion  *string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_link_v1_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *RegisterRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil && x.AgentVersion != nil {
		return *x.AgentVersion
	}
	return ""
}

// GetAgentManifestRequest identifies the target cluster for which
// the agent installation manifest should be generated.
type GetAgentManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cluster name the agent will register under.
	Cluster       *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentManifestRequest) Reset() {
	*x = GetAgentManifestRequest{}
	mi := &file_link_v1_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestRequest) ProtoMessage() {}

func (x *GetAgentManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentManifestRequest.ProtoReflect.Descriptor instead.
func (*GetAgentManifestRequest) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentManifestRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

// GetAgentManifestResponse contains the multi-document YAML manifest
// that can be applied via kubectl to install the agent.
type GetAgentManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Multi-document YAML containing Namespace, ServiceAccount,
	// ClusterRoleBinding, and Deployment resources.
	Manifest *string `protobuf:"bytes,1,opt,name=manifest" json:"manifest,omitempty"`
	// URL with an embedded HMAC token that serves the manifest as raw
	// YAML. Users can run `kubectl apply -f <url>` directly.
	Url           *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentManifestResponse) Reset() {
	*x = GetAgentManifestResponse{}
	mi := &file_link_v1_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentManifestResponse) ProtoMessage() {}

func (x *GetAgentManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentManifestResponse.ProtoReflect.Descriptor instead.
func (*GetAgentManifestResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentManifestResponse) GetManifest() string {
	if x != nil && x.Manifest != nil {
		return *x.Manifest
	}
	return ""
}

func (x *GetAgentManifestResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

// RegisterResponse contains a CA-signed certificate and the CA
// certificate so the agent can establish an mTLS tunnel connection.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The loopback endpoint reserved for this cluster tunnel.
	Endpoint *string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	// PEM-encoded X.509 certificate signed by the server's CA.
	Certificate []byte `protobuf:"bytes,2,opt,name=certificate" json:"certificate,omitempty"`
	// PEM-encoded CA certificate for verifying the tunnel server.
	CaCertificate []byte `protobuf:"bytes,3,opt,name=ca_certificate,json=caCertificate" json:"ca_certificate,omitempty"`
	// The version of the server binary (e.g. "v1.2.3"), set at build time.
	// Agents compare this against their own version to decide whether a
	// self-update is needed.
	ServerVersion *string `protobuf:"bytes,4,opt,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_link_v1_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_v1_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_link_v1_link_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *RegisterResponse) GetServerVersion() string {
	if x != nil && x.ServerVersion != nil {
		return *x.ServerVersion
	}
	return ""
}

var File_link_v1_link_proto protoreflect.FileDescriptor

const file_link_v1_link_proto_rawDesc = "" +
	"\n" +
	"\x12link/v1/link.proto\x12\x12otterscale.link.v1\x1a\rfeature.proto\"E\n" +
	"\x04Link\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\"\x12\n" +
	"\x10ListLinksRequest\"C\n" +
	"\x11ListLinksResponse\x12.\n" +
	"\x05links\x18\x01 \x03(\v2\x18.otterscale.link.v1.LinkR\x05links\"}\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\fR\x03csr\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"3\n" +
	"\x17GetAgentManifestRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"H\n" +
	"\x18GetAgentManifestResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\tR\bmanifest\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x9e\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\x12%\n" +
	"\x0eca_certificate\x18\x03 \x01(\fR\rcaCertificate\x12%\n" +
	"\x0eserver_version\x18\x04 \x01(\tR\rserverVersion2\xf0\x02\n" +
	"\vLinkService\x12m\n" +
	"\tListLinks\x12$.otterscale.link.v1.ListLinksRequest\x1a%.otterscale.link.v1.ListLinksResponse\"\x13\x8a\xdf\xd5\x1d\x0e\n" +
	"\flink-enabled\x12j\n" +
	"\bRegister\x12#.otterscale.link.v1.RegisterRequest\x1a$.otterscale.link.v1.RegisterResponse\"\x13\x8a\xdf\xd5\x1d\x0e\n" +
	"\flink-enabled\x12\x85\x01\n" +
	"\x10GetAgentManifest\x12+.otterscale.link.v1.GetAgentManifestRequest\x1a,.otterscale.link.v1.GetAgentManifestResponse\"\x16\x8a\xdf\xd5\x1d\x0e\n" +
	"\flink-enabled\x90\x02\x01B&Z$github.com/otterscale/api/link/v1;pbb\beditionsp\xe8\a"

var (
	file_link_v1_link_proto_rawDescOnce sync.Once
	file_link_v1_link_proto_rawDescData []byte
)

func file_link_v1_link_proto_rawDescGZIP() []byte {
	file_link_v1_link_proto_rawDescOnce.Do(func() {
		file_link_v1_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_v1_link_proto_rawDesc), len(file_link_v1_link_proto_rawDesc)))
	})
	return file_link_v1_link_proto_rawDescData
}

var file_link_v1_link_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_link_v1_link_proto_goTypes = []any{
	(*Link)(nil),                     // 0: otterscale.link.v1.Link
	(*ListLinksRequest)(nil),         // 1: otterscale.link.v1.ListLinksRequest
	(*ListLinksResponse)(nil),        // 2: otterscale.link.v1.ListLinksResponse
	(*RegisterRequest)(nil),          // 3: otterscale.link.v1.RegisterRequest
	(*GetAgentManifestRequest)(nil),  // 4: otterscale.link.v1.GetAgentManifestRequest
	(*GetAgentManifestResponse)(nil), // 5: otterscale.link.v1.GetAgentManifestResponse
	(*RegisterResponse)(nil),         // 6: otterscale.link.v1.RegisterResponse
}
var file_link_v1_link_proto_depIdxs = []int32{
	0, // 0: otterscale.link.v1.ListLinksResponse.links:type_name -> otterscale.link.v1.Link
	1, // 1: otterscale.link.v1.LinkService.ListLinks:input_type -> otterscale.link.v1.ListLinksRequest
	3, // 2: otterscale.link.v1.LinkService.Register:input_type -> otterscale.link.v1.RegisterRequest
	4, // 3: otterscale.link.v1.LinkService.GetAgentManifest:input_type -> otterscale.link.v1.GetAgentManifestRequest
	2, // 4: otterscale.link.v1.LinkService.ListLinks:output_type -> otterscale.link.v1.ListLinksResponse
	6, // 5: otterscale.link.v1.LinkService.Register:output_type -> otterscale.link.v1.RegisterResponse
	5, // 6: otterscale.link.v1.LinkService.GetAgentManifest:output_type -> otterscale.link.v1.GetAgentManifestResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_link_v1_link_proto_init() }
func file_link_v1_link_proto_init() {
	if File_link_v1_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_v1_link_proto_rawDesc), len(file_link_v1_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_v1_link_proto_goTypes,
		DependencyIndexes: file_link_v1_link_proto_depIdxs,
		MessageInfos:      file_link_v1_link_proto_msgTypes,
	}.Build()
	File_link_v1_link_proto = out.File
	file_link_v1_link_proto_goTypes = nil
	file_link_v1_link_proto_depIdxs = nil
}
