// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/runtime.proto

package pb

import (
	_ "github.com/otterscale/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PodLogRequest defines the parameters for streaming container logs.
// Fields align with corev1.PodLogOptions.
type PodLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// The namespace of the pod.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the pod.
	Name *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// The container name. If omitted, the first container in the pod is used.
	Container *string `protobuf:"bytes,4,opt,name=container" json:"container,omitempty"`
	// If true, stream logs as they are produced (like `kubectl logs -f`).
	Follow *bool `protobuf:"varint,5,opt,name=follow" json:"follow,omitempty"`
	// Number of lines from the end of the logs to show. If not set, all logs are shown.
	TailLines *int64 `protobuf:"varint,6,opt,name=tail_lines,json=tailLines" json:"tail_lines,omitempty"`
	// A relative time in seconds before the current time from which to show logs.
	SinceSeconds *int64 `protobuf:"varint,7,opt,name=since_seconds,json=sinceSeconds" json:"since_seconds,omitempty"`
	// An absolute time from which to show logs. Mutually exclusive with since_seconds.
	SinceTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=since_time,json=sinceTime" json:"since_time,omitempty"`
	// If true, return the logs for the previous terminated container instance.
	Previous *bool `protobuf:"varint,9,opt,name=previous" json:"previous,omitempty"`
	// If true, add an RFC3339 timestamp at the beginning of every line of log output.
	Timestamps *bool `protobuf:"varint,10,opt,name=timestamps" json:"timestamps,omitempty"`
	// Limit the number of bytes returned from the server.
	LimitBytes    *int64 `protobuf:"varint,11,opt,name=limit_bytes,json=limitBytes" json:"limit_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogRequest) Reset() {
	*x = PodLogRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogRequest) ProtoMessage() {}

func (x *PodLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogRequest.ProtoReflect.Descriptor instead.
func (*PodLogRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *PodLogRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *PodLogRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *PodLogRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PodLogRequest) GetContainer() string {
	if x != nil && x.Container != nil {
		return *x.Container
	}
	return ""
}

func (x *PodLogRequest) GetFollow() bool {
	if x != nil && x.Follow != nil {
		return *x.Follow
	}
	return false
}

func (x *PodLogRequest) GetTailLines() int64 {
	if x != nil && x.TailLines != nil {
		return *x.TailLines
	}
	return 0
}

func (x *PodLogRequest) GetSinceSeconds() int64 {
	if x != nil && x.SinceSeconds != nil {
		return *x.SinceSeconds
	}
	return 0
}

func (x *PodLogRequest) GetSinceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SinceTime
	}
	return nil
}

func (x *PodLogRequest) GetPrevious() bool {
	if x != nil && x.Previous != nil {
		return *x.Previous
	}
	return false
}

func (x *PodLogRequest) GetTimestamps() bool {
	if x != nil && x.Timestamps != nil {
		return *x.Timestamps
	}
	return false
}

func (x *PodLogRequest) GetLimitBytes() int64 {
	if x != nil && x.LimitBytes != nil {
		return *x.LimitBytes
	}
	return 0
}

// PodLogResponse contains a chunk of log data.
type PodLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw log data bytes.
	Data          []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogResponse) Reset() {
	*x = PodLogResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogResponse) ProtoMessage() {}

func (x *PodLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogResponse.ProtoReflect.Descriptor instead.
func (*PodLogResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *PodLogResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ExecuteTTYRequest defines the parameters for starting an interactive
// exec session in a container. Fields align with corev1.PodExecOptions.
type ExecuteTTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// The namespace of the pod.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the pod.
	Name *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// The container to exec into. If omitted, the first container is used.
	Container *string `protobuf:"bytes,4,opt,name=container" json:"container,omitempty"`
	// The command to execute (e.g. ["/bin/sh"]).
	Command []string `protobuf:"bytes,5,rep,name=command" json:"command,omitempty"`
	// If true, allocate a TTY for the exec session.
	Tty *bool `protobuf:"varint,6,opt,name=tty" json:"tty,omitempty"`
	// Initial terminal height in rows.
	Rows *uint32 `protobuf:"varint,7,opt,name=rows" json:"rows,omitempty"`
	// Initial terminal width in columns.
	Cols          *uint32 `protobuf:"varint,8,opt,name=cols" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTTYRequest) Reset() {
	*x = ExecuteTTYRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTTYRequest) ProtoMessage() {}

func (x *ExecuteTTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTTYRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTTYRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteTTYRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ExecuteTTYRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ExecuteTTYRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ExecuteTTYRequest) GetContainer() string {
	if x != nil && x.Container != nil {
		return *x.Container
	}
	return ""
}

func (x *ExecuteTTYRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecuteTTYRequest) GetTty() bool {
	if x != nil && x.Tty != nil {
		return *x.Tty
	}
	return false
}

func (x *ExecuteTTYRequest) GetRows() uint32 {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	return 0
}

func (x *ExecuteTTYRequest) GetCols() uint32 {
	if x != nil && x.Cols != nil {
		return *x.Cols
	}
	return 0
}

// ExecuteTTYResponse streams output from the exec session.
type ExecuteTTYResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session identifier, set only in the first response message.
	// Subsequent WriteTTY / ResizeTTY calls must reference this ID.
	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// Stdout data from the exec session.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	// Stderr data from the exec session (only when tty is false).
	Stderr        []byte `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTTYResponse) Reset() {
	*x = ExecuteTTYResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTTYResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTTYResponse) ProtoMessage() {}

func (x *ExecuteTTYResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTTYResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTTYResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteTTYResponse) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *ExecuteTTYResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecuteTTYResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

// WriteTTYRequest sends stdin data to an active exec session.
type WriteTTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session identifier returned in the first ExecuteTTYResponse.
	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// Stdin data to write.
	Stdin         []byte `protobuf:"bytes,2,opt,name=stdin" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTTYRequest) Reset() {
	*x = WriteTTYRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTTYRequest) ProtoMessage() {}

func (x *WriteTTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTTYRequest.ProtoReflect.Descriptor instead.
func (*WriteTTYRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *WriteTTYRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *WriteTTYRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

// ResizeTTYRequest updates the terminal dimensions of an exec session.
type ResizeTTYRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session identifier returned in the first ExecuteTTYResponse.
	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// New terminal height in rows.
	Rows *uint32 `protobuf:"varint,2,opt,name=rows" json:"rows,omitempty"`
	// New terminal width in columns.
	Cols          *uint32 `protobuf:"varint,3,opt,name=cols" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTTYRequest) Reset() {
	*x = ResizeTTYRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTTYRequest) ProtoMessage() {}

func (x *ResizeTTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTTYRequest.ProtoReflect.Descriptor instead.
func (*ResizeTTYRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ResizeTTYRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *ResizeTTYRequest) GetRows() uint32 {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	return 0
}

func (x *ResizeTTYRequest) GetCols() uint32 {
	if x != nil && x.Cols != nil {
		return *x.Cols
	}
	return 0
}

// PortForwardRequest defines the parameters for starting a port-forward session.
type PortForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// The namespace of the pod.
	Namespace *string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the pod.
	Name *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// The container port to forward to.
	Port          *int32 `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardRequest) Reset() {
	*x = PortForwardRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRequest) ProtoMessage() {}

func (x *PortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardRequest.ProtoReflect.Descriptor instead.
func (*PortForwardRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *PortForwardRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *PortForwardRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *PortForwardRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PortForwardRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

// PortForwardResponse streams data received from the forwarded port.
type PortForwardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session identifier, set only in the first response message.
	// Subsequent WritePortForward calls must reference this ID.
	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// Data received from the forwarded port on the pod.
	Data          []byte `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardResponse) Reset() {
	*x = PortForwardResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardResponse) ProtoMessage() {}

func (x *PortForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardResponse.ProtoReflect.Descriptor instead.
func (*PortForwardResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *PortForwardResponse) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *PortForwardResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WritePortForwardRequest sends data to an active port-forward session.
type WritePortForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session identifier returned in the first PortForwardResponse.
	SessionId *string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// Data to send to the forwarded port on the pod.
	Data          []byte `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePortForwardRequest) Reset() {
	*x = WritePortForwardRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePortForwardRequest) ProtoMessage() {}

func (x *WritePortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePortForwardRequest.ProtoReflect.Descriptor instead.
func (*WritePortForwardRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *WritePortForwardRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *WritePortForwardRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ScaleRequest defines the parameters for scaling a workload.
// Uses the Kubernetes /scale subresource for correctness.
type ScaleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps").
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the workload.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the workload.
	Name *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	// The desired number of replicas.
	Replicas      *int32 `protobuf:"varint,7,opt,name=replicas" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleRequest) Reset() {
	*x = ScaleRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleRequest) ProtoMessage() {}

func (x *ScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleRequest.ProtoReflect.Descriptor instead.
func (*ScaleRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *ScaleRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ScaleRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *ScaleRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ScaleRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *ScaleRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ScaleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ScaleRequest) GetReplicas() int32 {
	if x != nil && x.Replicas != nil {
		return *x.Replicas
	}
	return 0
}

// ScaleResponse contains the updated replica count after scaling.
type ScaleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current number of replicas after the scale operation.
	Replicas      *int32 `protobuf:"varint,1,opt,name=replicas" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleResponse) Reset() {
	*x = ScaleResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleResponse) ProtoMessage() {}

func (x *ScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleResponse.ProtoReflect.Descriptor instead.
func (*ScaleResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *ScaleResponse) GetReplicas() int32 {
	if x != nil && x.Replicas != nil {
		return *x.Replicas
	}
	return 0
}

// RestartRequest defines the parameters for triggering a rolling restart.
// This patches the pod template annotation with kubectl.kubernetes.io/restartedAt,
// equivalent to `kubectl rollout restart`.
type RestartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target Kubernetes cluster identifier.
	Cluster *string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	// Kubernetes API Group (e.g., "apps").
	Group *string `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	// Kubernetes API Version (e.g., "v1").
	Version *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// Kubernetes API Resource name in plural (e.g., "deployments").
	Resource *string `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	// The namespace of the workload.
	Namespace *string `protobuf:"bytes,5,opt,name=namespace" json:"namespace,omitempty"`
	// The name of the workload.
	Name          *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() {
	*x = RestartRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRequest) ProtoMessage() {}

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *RestartRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *RestartRequest) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *RestartRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *RestartRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *RestartRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *RestartRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x18runtime/v1/runtime.proto\x12\x15otterscale.runtime.v1\x1a\rfeature.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x02\n" +
	"\rPodLogRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x06 \x01(\x03R\ttailLines\x12#\n" +
	"\rsince_seconds\x18\a \x01(\x03R\fsinceSeconds\x129\n" +
	"\n" +
	"since_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tsinceTime\x12\x1a\n" +
	"\bprevious\x18\t \x01(\bR\bprevious\x12\x1e\n" +
	"\n" +
	"timestamps\x18\n" +
	" \x01(\bR\n" +
	"timestamps\x12\x1f\n" +
	"\vlimit_bytes\x18\v \x01(\x03R\n" +
	"limitBytes\"$\n" +
	"\x0ePodLogResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xd1\x01\n" +
	"\x11ExecuteTTYRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x06 \x01(\bR\x03tty\x12\x12\n" +
	"\x04rows\x18\a \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\b \x01(\rR\x04cols\"c\n" +
	"\x12ExecuteTTYResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\"F\n" +
	"\x0fWriteTTYRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\"Y\n" +
	"\x10ResizeTTYRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\"t\n" +
	"\x12PortForwardRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"H\n" +
	"\x13PortForwardResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"L\n" +
	"\x17WritePortForwardRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xc2\x01\n" +
	"\fScaleRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1a\n" +
	"\breplicas\x18\a \x01(\x05R\breplicas\"+\n" +
	"\rScaleResponse\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\"\xa8\x01\n" +
	"\x0eRestartRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name2\x8a\a\n" +
	"\x0eRuntimeService\x12o\n" +
	"\x06PodLog\x12$.otterscale.runtime.v1.PodLogRequest\x1a%.otterscale.runtime.v1.PodLogResponse\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled0\x01\x12{\n" +
	"\n" +
	"ExecuteTTY\x12(.otterscale.runtime.v1.ExecuteTTYRequest\x1a).otterscale.runtime.v1.ExecuteTTYResponse\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled0\x01\x12b\n" +
	"\bWriteTTY\x12&.otterscale.runtime.v1.WriteTTYRequest\x1a\x16.google.protobuf.Empty\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled\x12d\n" +
	"\tResizeTTY\x12'.otterscale.runtime.v1.ResizeTTYRequest\x1a\x16.google.protobuf.Empty\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled\x12~\n" +
	"\vPortForward\x12).otterscale.runtime.v1.PortForwardRequest\x1a*.otterscale.runtime.v1.PortForwardResponse\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled0\x01\x12r\n" +
	"\x10WritePortForward\x12..otterscale.runtime.v1.WritePortForwardRequest\x1a\x16.google.protobuf.Empty\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled\x12j\n" +
	"\x05Scale\x12#.otterscale.runtime.v1.ScaleRequest\x1a$.otterscale.runtime.v1.ScaleResponse\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabled\x12`\n" +
	"\aRestart\x12%.otterscale.runtime.v1.RestartRequest\x1a\x16.google.protobuf.Empty\"\x16\x8a\xdf\xd5\x1d\x11\n" +
	"\x0fruntime-enabledB)Z'github.com/otterscale/api/runtime/v1;pbb\beditionsp\xe8\a"

var (
	file_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_runtime_v1_runtime_proto_rawDescData []byte
)

func file_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_runtime_proto_rawDesc), len(file_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_runtime_v1_runtime_proto_rawDescData
}

var file_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_runtime_v1_runtime_proto_goTypes = []any{
	(*PodLogRequest)(nil),           // 0: otterscale.runtime.v1.PodLogRequest
	(*PodLogResponse)(nil),          // 1: otterscale.runtime.v1.PodLogResponse
	(*ExecuteTTYRequest)(nil),       // 2: otterscale.runtime.v1.ExecuteTTYRequest
	(*ExecuteTTYResponse)(nil),      // 3: otterscale.runtime.v1.ExecuteTTYResponse
	(*WriteTTYRequest)(nil),         // 4: otterscale.runtime.v1.WriteTTYRequest
	(*ResizeTTYRequest)(nil),        // 5: otterscale.runtime.v1.ResizeTTYRequest
	(*PortForwardRequest)(nil),      // 6: otterscale.runtime.v1.PortForwardRequest
	(*PortForwardResponse)(nil),     // 7: otterscale.runtime.v1.PortForwardResponse
	(*WritePortForwardRequest)(nil), // 8: otterscale.runtime.v1.WritePortForwardRequest
	(*ScaleRequest)(nil),            // 9: otterscale.runtime.v1.ScaleRequest
	(*ScaleResponse)(nil),           // 10: otterscale.runtime.v1.ScaleResponse
	(*RestartRequest)(nil),          // 11: otterscale.runtime.v1.RestartRequest
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_runtime_v1_runtime_proto_depIdxs = []int32{
	12, // 0: otterscale.runtime.v1.PodLogRequest.since_time:type_name -> google.protobuf.Timestamp
	0,  // 1: otterscale.runtime.v1.RuntimeService.PodLog:input_type -> otterscale.runtime.v1.PodLogRequest
	2,  // 2: otterscale.runtime.v1.RuntimeService.ExecuteTTY:input_type -> otterscale.runtime.v1.ExecuteTTYRequest
	4,  // 3: otterscale.runtime.v1.RuntimeService.WriteTTY:input_type -> otterscale.runtime.v1.WriteTTYRequest
	5,  // 4: otterscale.runtime.v1.RuntimeService.ResizeTTY:input_type -> otterscale.runtime.v1.ResizeTTYRequest
	6,  // 5: otterscale.runtime.v1.RuntimeService.PortForward:input_type -> otterscale.runtime.v1.PortForwardRequest
	8,  // 6: otterscale.runtime.v1.RuntimeService.WritePortForward:input_type -> otterscale.runtime.v1.WritePortForwardRequest
	9,  // 7: otterscale.runtime.v1.RuntimeService.Scale:input_type -> otterscale.runtime.v1.ScaleRequest
	11, // 8: otterscale.runtime.v1.RuntimeService.Restart:input_type -> otterscale.runtime.v1.RestartRequest
	1,  // 9: otterscale.runtime.v1.RuntimeService.PodLog:output_type -> otterscale.runtime.v1.PodLogResponse
	3,  // 10: otterscale.runtime.v1.RuntimeService.ExecuteTTY:output_type -> otterscale.runtime.v1.ExecuteTTYResponse
	13, // 11: otterscale.runtime.v1.RuntimeService.WriteTTY:output_type -> google.protobuf.Empty
	13, // 12: otterscale.runtime.v1.RuntimeService.ResizeTTY:output_type -> google.protobuf.Empty
	7,  // 13: otterscale.runtime.v1.RuntimeService.PortForward:output_type -> otterscale.runtime.v1.PortForwardResponse
	13, // 14: otterscale.runtime.v1.RuntimeService.WritePortForward:output_type -> google.protobuf.Empty
	10, // 15: otterscale.runtime.v1.RuntimeService.Scale:output_type -> otterscale.runtime.v1.ScaleResponse
	13, // 16: otterscale.runtime.v1.RuntimeService.Restart:output_type -> google.protobuf.Empty
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_runtime_v1_runtime_proto_init() }
func file_runtime_v1_runtime_proto_init() {
	if File_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_runtime_proto_rawDesc), len(file_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_v1_runtime_proto_depIdxs,
		MessageInfos:      file_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_runtime_v1_runtime_proto = out.File
	file_runtime_v1_runtime_proto_goTypes = nil
	file_runtime_v1_runtime_proto_depIdxs = nil
}
