// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file feature.proto (package otterscale.api, edition 2023)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file feature.proto.
 */
export const file_feature: GenFile = /*@__PURE__*/
  fileDesc("Cg1mZWF0dXJlLnByb3RvEg5vdHRlcnNjYWxlLmFwaSIXCgdGZWF0dXJlEgwKBG5hbWUYASABKAk6VAoHZmVhdHVyZRIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGPHb2gMgASgLMhcub3R0ZXJzY2FsZS5hcGkuRmVhdHVyZVIHZmVhdHVyZUIbWhlnaXRodWIuY29tL290dGVyc2NhbGUvYXBpYghlZGl0aW9uc3DoBw", [file_google_protobuf_descriptor]);

/**
 * @generated from message otterscale.api.Feature
 */
export type Feature = Message<"otterscale.api.Feature"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message otterscale.api.Feature.
 * Use `create(FeatureSchema)` to create a new message.
 */
export const FeatureSchema: GenMessage<Feature> = /*@__PURE__*/
  messageDesc(file_feature, 0);

/**
 * @generated from extension: otterscale.api.Feature feature = 7777777;
 */
export const feature: GenExtension<MethodOptions, Feature> = /*@__PURE__*/
  extDesc(file_feature, 0);

